=== GuillermoSH/1oDAW/LND/Ejercicios/Segundo Trimestre/BDFacultades.dtd
<!ELEMENT BDFacultades (facultades,investigadores,equipos,reservas)>
    <!ELEMENT facultades (facultad+)>
        <!ELEMENT facultad (nombre)>
            <!ELEMENT nombre (#PCDATA)>
            <!ATTLIST facultad CÃ³digo CDATA #REQUIRED>

    <!ELEMENT investigadores (investigador+)>
        <!ELEMENT investigador (NomApell,facultad)>
            <!ELEMENT NomApell (#PCDATA)>
            <!ATTLIST investigador DNI CDATA #REQUIRED>

    <!ELEMENT equipos (equipo+)>
        <!ELEMENT equipo (Nombre,facultad)>
            <!ELEMENT Nombre (#PCDATA)>
            <!ATTLIST equipo NumSerie CDATA #REQUIRED>
    
    <!ELEMENT reservas (reserva+)>
        <!ELEMENT reserva (comienzo,fin)>
            <!ELEMENT comienzo (#PCDATA)>
            <!ELEMENT fin (#PCDATA)>
            <!ATTLIST investigador DNI CDATA #REQUIRED>
            <!ATTLIST equipo NumSerie CDATA #REQUIRED>

=== GuillermoSH/1oDAW/LND/Ejercicios/Segundo Trimestre/BDFacultades.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BDFacultades SYSTEM "BDFacultades.dtd">
<BDFacultades>
    <facultades>
        <facultad Código="1">
            <nombre>ESIT</nombre>
        </facultad>
    </facultades>
    
    <investigadores>
        <investigador DNI="12345678W">
            <NomApell>Antonio Pérez</NomApell>
            <facultad Código="1"><nombre>ESIT</nombre></facultad>
        </investigador>
    </investigadores>
    
    <equipos>
        <equipo NumSerie="123">
            <Nombre>InvestigadoresAlPoder</Nombre>
            <facultad Código="1"><nombre>ESIT</nombre></facultad>
        </equipo>
    </equipos>
    
    <reservas>
        <reserva>
            <comienzo>18-2-2021 18:00</comienzo>
            <fin>18-2-2021 20:30</fin>
        </reserva>
    </reservas>
</BDFacultades>
