=== GuillermoSH/1oDAW/LND/Ejercicios/Segundo Trimestre/BDHospital.dtd
<!ELEMENT BDHospital (hospitales,salas,plantillas,ocupacion,doctores,enfermos)>
    <!ELEMENT hospitales (hospital+)>
        <!ELEMENT hospital (nombre,direccion,telefono,num_camas)>
            <!ELEMENT nombre (#PCDATA)>
            <!ELEMENT direccion (#PCDATA)>
            <!ELEMENT telefono (#PCDATA)>
            <!ELEMENT num_camas (#PCDATA)>
            <!ATTLIST hospital hospital_cod CDATA #REQUIRED>

    <!ELEMENT salas (sala+)>
        <!ELEMENT sala (nombre,num_cama)>
            <!ELEMENT num_cama (#PCDATA)>
            <!ATTLIST hospital hospital_cod IDREF #REQUIRED>
            <!ATTLIST sala sala_cod CDATA #REQUIRED>

    <!ELEMENT plantillas (plantilla+)>
        <!ELEMENT plantilla (apellido,funcion,turno,salario)>
            <!ELEMENT apellido (#PCDATA)>
            <!ELEMENT funcion (#PCDATA)>
            <!ELEMENT turno (#PCDATA)>
            <!ELEMENT salario (#PCDATA)>
            <!ATTLIST hospital hospital_cod IDREF #REQUIRED>
            <!ATTLIST sala sala_cod IDREF #REQUIRED>
            <!ATTLIST plantilla empleado_num CDATA #REQUIRED>

    <!ELEMENT ocupacion (cama)>
        <!ELEMENT cama (#PCDATA)>
        <!ATTLIST hospital hospital_cod IDREF #REQUIRED>
        <!ATTLIST sala sala_cod IDREF #REQUIRED>
        <!ATTLIST ocupacion inscripcion CDATA #REQUIRED>

    <!ELEMENT doctores (doctor+)>
        <!ELEMENT doctor (apellido,especialidad)>
            <!ELEMENT especialidad (#PCDATA)>
            <!ATTLIST hospital hospital_cod IDREF #REQUIRED>
            <!ATTLIST doctor doctor_num CDATA #REQUIRED>

    <!ELEMENT enfermos (enfermo+)>
        <!ELEMENT enfermo (apellido,direccion,fecha_nac,s)>
            <!ELEMENT fecha_nac (#PCDATA)>
            <!ELEMENT s (#PCDATA)>
            <!ATTLIST ocupacion inscripcion IDREF #REQUIRED>
            <!ATTLIST enfermo nss CDATA #REQUIRED>

=== GuillermoSH/1oDAW/LND/Ejercicios/Segundo Trimestre/BDHospital.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BDHospital SYSTEM "BDHospital.dtd">
<BDHospital>
    <hospitales>
        <hospital hospital_cod="1">
            <nombre>Hospital Universitario de Canarias</nombre>
            <direccion>C/Por ahi nº1 San Cristobal de la Laguna, Santa Cruz de Tenerife</direccion>
            <telefono>123456789</telefono>
            <num_camas>164</num_camas>
        </hospital>
    </hospitales>
    
    <salas>
        <sala sala_cod="1">
            <nombre>Sala Pediatría</nombre>
            <num_cama>12</num_cama>
        </sala>
    </salas>
    
    <plantillas>
        <plantilla empleado_num="321">
            <apellido>Pérez</apellido>
            <funcion>Administración</funcion>
            <turno>Primer turno</turno>
            <salario>1352.54</salario>
        </plantilla>
    </plantillas>
    
    <ocupacion inscripcion="123">
        <cama>13</cama>
    </ocupacion>

    <doctores>
        <doctor doctor_num="1">
            <apellido>Hernández</apellido>
            <especialidad>Pediatría</especialidad>
        </doctor>
    </doctores>

    <enfermos>
        <enfermo nss="73512">
            <apellido>Matos</apellido>
            <direccion>C/Los espaguetis nº45 La Orotava, Santa Cruz de Tenerife</direccion>
            <fecha_nac>31-01-1965</fecha_nac>
            <s>No se que es</s>
        </enfermo>
    </enfermos>
</BDHospital>
