=== GuillermoSH/1oDAW/LND/Ejercicios/Segundo Trimestre/BDProveedores.dtd
<!ELEMENT BDProveedores (proveedores,items,pedidos,clientes)>
    <!ELEMENT proveedores (proveedor+)>
        <!ELEMENT proveedor (nom_p,ciud_p)>
            <!ATTLIST proveedor nro_pro CDATA #REQUIRED
                                Categoría (Alimentación|Muebles|Tecnología|Limpieza|Textil|Jardinería|Playa|Deportes|Ferretería) #REQUIRED>
            <!ELEMENT nom_p (#PCDATA)>
            <!ELEMENT ciud_p (#PCDATA)>

    <!ELEMENT items (item+)>
        <!ELEMENT item (descripcion_i,ciudad_i)>
            <!ATTLIST item nro_i CDATA #REQUIRED>
            <!ELEMENT descripcion_i (#PCDATA)>
            <!ELEMENT ciudad_i (#PCDATA)>

    <!ELEMENT pedidos (pedido+)>
        <!ELEMENT pedido (nro_c,nro_i,nro_pro,cantidad,precio)>
            <!ATTLIST pedido nro_pe CDATA #REQUIRED>
            <!ELEMENT nro_c (#PCDATA)>
            <!ELEMENT nro_i (#PCDATA)>
            <!ELEMENT nro_pro (#PCDATA)>
            <!ELEMENT cantidad (#PCDATA)>
            <!ELEMENT precio (#PCDATA)>

    <!ELEMENT clientes (cliente+)>
        <!ELEMENT cliente (nom_c,ciudad_c)>
            <!ATTLIST cliente nro_c CDATA #REQUIRED>
            <!ELEMENT nom_c (#PCDATA)>
            <!ELEMENT ciudad_c (#PCDATA)>

=== GuillermoSH/1oDAW/LND/Ejercicios/Segundo Trimestre/BDProveedores.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE BDProveedores SYSTEM "BDProveedores.dtd">
<BDProveedores>
    <proveedores>
        <proveedor Categoría="Alimentación" nro_pro="1">
            <nom_p>Antonio</nom_p>
            <ciud_p>Madrid</ciud_p>
        </proveedor>
    </proveedores>

    <items>
        <item nro_i="1">
            <descripcion_i>Manzana Reineta de alta calidad</descripcion_i>
            <ciudad_i>Salamanca</ciudad_i>
        </item>
    </items>

    <pedidos>
        <pedido nro_pe="1">
            <nro_c>1</nro_c>
            <nro_i>1</nro_i>
            <nro_pro>1</nro_pro>
            <cantidad>453</cantidad>
            <precio>648.12</precio>
        </pedido>
    </pedidos>
    
    <clientes>
        <cliente nro_c="1">
            <nom_c>Fulanito</nom_c>
            <ciudad_c>Cuenca</ciudad_c>
        </cliente>
    </clientes>
</BDProveedores>
