=== GuillermoSH/1oDAW/LND/Ejercicios/Segundo Trimestre/dibujo.dtd
<!ELEMENT dibujo (figura+)>   
    <!ELEMENT figura (circulo | cuadrado)>
        <!ELEMENT circulo (centro,radio)>
        <!ELEMENT centro (#PCDATA)>
        <!ELEMENT radio (#PCDATA)>
    <!ELEMENT cuadrado (lado)>
        <!ELEMENT lado (#PCDATA)>

=== GuillermoSH/1oDAW/LND/Ejercicios/Segundo Trimestre/dibujo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dibujo SYSTEM "dibujo.dtd">
<dibujo>
    <figura>
        <circulo>
            <centro>1.5</centro>
            <radio>5.5</radio>
        </circulo>
    </figura>
    <figura>
        <cuadrado>
            <lado>2</lado>
        </cuadrado>
    </figura>
</dibujo>
